// Auto-generated by scripts/generate-security-config.js
// Do not edit directly. Source: permissions-policy.txt

export const PERMISSIONS_POLICY =
	'accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=()';
